[package]
name = "benchmark"
version = "0.1.0"
authors = ["negamartin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midly_old = { path = "../.." }
midly_smf = { path = ".." }
rimd = "0.0"
nom-midi = "0.5"
